name: React Components Tests
on: [push]
jobs:
  Component-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event."
      - run: echo "Job is running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The name of the banch is ${{ github.ref }} in the ${{ github.reposiotory }} repository."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The repository ${{ github.repository }} has been cloned to the runner."
      - run: echo "Workflow is ready to test code on the runner."
